### ISSUE TITLE
Homeassistant MQTT topic

### ISSUE THREAD

**Issue by alexsahka** [thingzi/thingzi-logic-climate#10] opened 2024-04-01 03:00 UTC
Can you help me find the Home Assistant MQTT topic for climate control? I've tried everything I can think of, but I'm not seeing any climate controllers in either Home Assistant or the MQTT broker.

![image](https://github.com/thingzi/thingzi-logic-climate/assets/7469537/dd4dfcf5-68d6-48b4-9c8b-cd2ddb40cefc)

![image](https://github.com/thingzi/thingzi-logic-climate/assets/7469537/03718901-f587-4e4b-b7bc-75061f277eba)

**Comment by bryzix** [comment] 2024-04-01 10:24
Can you share the node config using the node red export please and I will double check.  It should be in mqtt with the settings you have so this will help me diagnose the issue.

**Comment by alexsahka** [comment] 2024-04-01 15:37
> Can you share the node config using the node red export please and I will double check. It should be in mqtt with the settings you have so this will help me diagnose the issue.

Here is the node config:
![image](https://github.com/thingzi/thingzi-logic-climate/assets/7469537/14b81375-956a-4730-8611-2ff72fe8a8f5)


`[{"id":"7809a45a2b053a77","type":"thingzi-climate","z":"ae7a451615589173","name":"ghheater","climateType":"heat","sendStatus":true,"keepAlive":"1","cycleDelay":30,"boostDuration":30,"defaultPreset":"","degrees":"F","defaultSetPoint":"70","tolerance":"0.3","minTemp":"30","maxTemp":"70","tempValid":60,"swapDelay":60,"onPayloadType":"str","onPayload":"ON","offPayloadType":"str","offPayload":"OFF","advertiseType":"hass","advertise":true,"broker":"5aeb1c10233e4cc2","topic":"homeassistant/climate","outputs":3,"x":800,"y":2160,"wires":[["250d96961925e207"],["9106d39512c3fb77"],["e0687c3e958986ea"]]},{"id":"250d96961925e207","type":"debug","z":"ae7a451615589173","name":"debug 493","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1010,"y":2120,"wires":[]},{"id":"9106d39512c3fb77","type":"debug","z":"ae7a451615589173","name":"debug 494","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1010,"y":2160,"wires":[]},{"id":"e0687c3e958986ea","type":"debug","z":"ae7a451615589173","name":"debug 499","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1010,"y":2200,"wires":[]},{"id":"87ec1a7113278282","type":"inject","z":"ae7a451615589173","name":"Setpoint 70","props":[{"p":"setpoint","v":"70","vt":"num"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":610,"y":2160,"wires":[["7809a45a2b053a77"]]},{"id":"06a917e26668268a","type":"inject","z":"ae7a451615589173","name":"Temp 67","props":[{"p":"temp","v":"67","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":600,"y":2200,"wires":[["7809a45a2b053a77"]]},{"id":"5aeb1c10233e4cc2","type":"mqtt-broker","name":"MQTT 100","broker":"10.90.0.100","port":"1883","clientid":"","autoConnect":true,"usetls":false,"protocolVersion":"4","keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"1","birthRetain":"true","birthPayload":"","birthMsg":{},"closeTopic":"","closeQos":"1","closeRetain":"true","closePayload":"","closeMsg":{},"willTopic":"","willQos":"1","willRetain":"true","willPayload":"","willMsg":{},"userProps":"","sessionExpiry":""}]`

**Comment by bryzix** [comment] 2024-04-01 21:14
Hi so ive checked your setup and first thing to change (not really related to your issue) is the root topic.  This is for the actual device values and should not be in the homeassistant topic as this will confuse HASS.  A good example for this would be "devices" (the node is appended) which would look like...

<img width="177" alt="image" src="https://github.com/thingzi/thingzi-logic-climate/assets/46371227/a9d8809a-b76a-4edc-acaa-82af4d336066">
<br>
<img width="154" alt="image" src="https://github.com/thingzi/thingzi-logic-climate/assets/46371227/ee9bdaa2-78db-49b2-9753-911e945b101f">
<br><br>

Related to your main issue of not showing in MQTT, if it doesn't show in MQTT it wont show in HASS so best to validate MQTT first.  By default device discovery for HASS will be in the homeassistant topic (not related to the root topic setting) e.g.

<img width="446" alt="image" src="https://github.com/thingzi/thingzi-logic-climate/assets/46371227/187e961a-db3b-42a5-ac2d-edbe918e3421">

MQTT topics worked fine for the nodes you shared on my broker so If its not appearing for you its worth checking node red is connecting properly to MQTT.  The climate node uses the standard nodered MQTT broker connection so you can use an MQTT out node to test for any connection issues...

<img width="368" alt="image" src="https://github.com/thingzi/thingzi-logic-climate/assets/46371227/5dcafb76-62cf-433b-a9ae-56c1988aed94">

**Comment by alexsahka** [comment] 2024-04-01 21:36
> Hi so ive checked your setup and first thing to change (not really related to your issue) is the root topic. This is for the actual device values and should not be in the homeassistant topic as this will confuse HASS. A good example for this would be "devices" (the node is appended) which would look like...
> 
I've been using this setup for at least 4-5 years without any MQTT issues. Here are some screenshots showing that the Node-RED to MQTT communication seems to be functioning correctly.

![image](https://github.com/thingzi/thingzi-logic-climate/assets/7469537/813eb193-ae32-42d5-8a3b-f024831868f7)

![image](https://github.com/thingzi/thingzi-logic-climate/assets/7469537/7f4539c8-5c20-460c-a80a-b1a3e43c3954)

**Comment by bryzix** [comment] 2024-04-02 08:45
Is there a ghheater-climate topic inside homeassistsnt/climate on your broker?

On the topic location for values  my understanding is that the homeassistant topic is for discovery topics only, not for values and so while this may work ok it will probably fill your HASS log with errors.

**Comment by alexsahka** [comment] 2024-04-02 19:07
> Is there a ghheater-climate topic inside homeassistsnt/climate on your broker?
> 
> On the topic location for values my understanding is that the homeassistant topic is for discovery topics only, not for values and so while this may work ok it will probably fill your HASS log with errors.

No 'ghheater-climate' topic found in homeassistant/climate. This is why I reported the issue.

**Comment by bryzix** [comment] 2024-04-02 20:03
Last thing to check, have you tried creating a new climate node with similar config.  If that does not work I will see if I can prepare a build with more debug output to diagnose the issue.  Out of interest have you upgraded the climate node recently or did it just stop working?

**Comment by alexsahka** [comment] 2024-04-03 03:21
> Last thing to check, have you tried creating a new climate node with similar config. If that does not work I will see if I can prepare a build with more debug output to diagnose the issue. Out of interest have you upgraded the climate node recently or did it just stop working?

I believe I've identified the problem! It seems like Node-RED needs to be rebooted after installing the thingzi-climate node. Typically, Node-RED would warn about the need to reboot after installing certain nodes, but it appears that didn't happen in this case.

**Comment by alexsahka** [comment] 2024-04-03 03:32
> Last thing to check, have you tried creating a new climate node with similar config. If that does not work I will see if I can prepare a build with more debug output to diagnose the issue. Out of interest have you upgraded the climate node recently or did it just stop working?

It seems there's an issue with the thingzi-climate node.  I need to reboot Node-RED every single time I add a new thingzi-climate node to a flow.  Also, any changes made to the settings of a thingzi-climate node require a Node-RED reboot for the changes to take effect in the MQTT broker.

**Comment by bryzix** [comment] 2024-04-03 10:14
Sounds strange. Are you able to get the logs from the node red server?  Usually if there is an error like this there would be a clue in there.  

It could be related to the state of an existing node so you could also try to disable existing nodes and adding new ones to see if you see the same behaviour.  

If there is something in the logs it's usually a quick fix.

**Comment by alexsahka** [comment] 2024-04-03 16:12
> Sounds strange. Are you able to get the logs from the node red server? Usually if there is an error like this there would be a clue in there.
> 
> It could be related to the state of an existing node so you could also try to disable existing nodes and adding new ones to see if you see the same behaviour.
> 
> If there is something in the logs it's usually a quick fix.

Zero errors in the Nodered log

**Comment by alexsahka** [comment] 2024-04-03 16:20
> Sounds strange. Are you able to get the logs from the node red server? Usually if there is an error like this there would be a clue in there.
> 
> It could be related to the state of an existing node so you could also try to disable existing nodes and adding new ones to see if you see the same behaviour.
> 
> If there is something in the logs it's usually a quick fix.

I also tried using a completely clean, brand new Node-RED installation in Docker and encountered the same issue. Have you ever tried installing the latest thingzi-climate node on a fresh Node-RED installation?

**Comment by bryzix** [comment] 2024-04-03 16:38
I do this regularly as I test via fresh docker containers.  

I will try latest node red again though and look to add some extra checks and debug logging.  Will probably take me a few days.

**Comment by alexsahka** [comment] 2024-04-03 21:30
> I do this regularly as I test via fresh docker containers.
> 
> I will try latest node red again though and look to add some extra checks and debug logging. Will probably take me a few days.

Any requirements for the MQTT server? My is V3.1.1

![image](https://github.com/thingzi/thingzi-logic-climate/assets/7469537/c340088d-278f-463e-9937-d6166ee07e41)

**Comment by bryzix** [comment] 2024-04-03 22:52
Nope, it uses the node red 
Default mqtt nodes so will check this link is working on latest.  I will give everything a review to see what I find.

**Comment by bryzix** [comment] 2024-04-05 16:08
so the good news is that ive managed to re-create your issue using your export on a clean build with no existing data o the latest node red.  Hopefully i should be able to identify the issue from here

**Comment by bryzix** [comment] 2024-04-07 12:51
Hi, so it seems the reproduction wasnt as anticipated as it was a connection issue :(

However i have performed a test using the following approach and did find an issue that may be related...

- Create brand new home assistant set up with hass, mosquitto & node red
- Link HASS to mosquitto for MQTT discovery
- Install the v1.0.4 of the thingzi climate node
- Import your node example, changing the server to mosquitto and the the root node location to "test"
- Add 2 extra climate nodes with varied configuration

From the above i was able to confirm that the MQTT advertising worked, however there was a bug that would have prevented the node appearing in hass which was in the hass error output.  I have fixed this bug and released version 1.0.5. 

This still does not explain why you could not see any entries in MQTT but i have not been able to reproduce this issue or any loss of connection once configured properly.  Ive tested restarts and multiple changes / deploys.

To be sure, I would still strongly recommend changing the root topic location you have set as placing non discovery topics in homeassistant/climate will likely spam the HASS logs with false positives and its possible a future hass feature could be added to keep this topic tidy.

**Comment by bryzix** [comment] 2024-04-07 13:21
also as a side note, i am currently working on 1.0.6 which will have some more debug logging around connection issues

Edit: this version is up and adds some log elements to node red console showing if advertising is attempted and also prints any errors from mqtt publishing that could highlight any issues.

**Comment by alexsahka** [comment] 2024-04-07 21:30
> also as a side note, i am currently working on 1.0.6 which will have some more debug logging around connection issues
> 
> Edit: this version is up and adds some log elements to node red console showing if advertising is attempted and also prints any errors from mqtt publishing that could highlight any issues.

Thanks! After the update, the thermostat now shows up in Home Assistant. However, changes made to the node settings, such as switching from heat only to cool only etc., aren't reflected in Home Assistant or MQTT until I reboot Node-RED.


I'm using the [node-red-contrib-ha-mqtt](https://flows.nodered.org/node/node-red-contrib-ha-mqtt) node as well, It communicates with Home Assistant via MQTT and utilizes an Auto-discovery node that requires activation after any changes are made to this set of nodes.
![image](https://github.com/thingzi/thingzi-logic-climate/assets/7469537/154ae754-1993-47ab-8042-41801f70b9ec)
![image](https://github.com/thingzi/thingzi-logic-climate/assets/7469537/64a69c19-4d72-4ab4-8042-b3110a652313)

**Comment by bryzix** [comment] 2024-04-08 08:22
At least that's a step forward 😄

If you installed 1.0.6 do you get any errors in node red after it stops working (either in the debug tab or on the server console where it's running eg docker)? I added some output for send errors which may be helpful.  Given what you described ie working initially then never again until a reboot it could be a conflict with another node or capacity issue but I'd expect to see sone errors.

I'm sure you are also aware but the node is designed to have a delay between any change to protect HVAC equipment from rapid changes.  When you see an asterix on the node status, a change is pending but it won't have been updated in MQTT.

Lastly what's the thinking for using that hass discovery node? I've never needed to do this and just added the MQTT extension in HASS settings to connect directly to MQTT.

**Comment by alexsahka** [comment] 2024-04-08 16:04
I havent seen any errors and node never stop working, but when i change any settings in the node no changes in the HA or MQTT and 20 hours later there still no updates . 

> At least that's a step forward 😄
> 
> If you installed 1.0.6 do you get any errors in node red after it stops working (either in the debug tab or on the server console where it's running eg docker)? I added some output for send errors which may be helpful. Given what you described ie working initially then never again until a reboot it could be a conflict with another node or capacity issue but I'd expect to see sone errors.
> 
> I'm sure you are also aware but the node is designed to have a delay between any change to protect HVAC equipment from rapid changes. When you see an asterix on the node status, a change is pending but it won't have been updated in MQTT.
> 
> Lastly what's the thinking for using that hass discovery node? I've never needed to do this and just added the MQTT extension in HASS settings to connect directly to MQTT.

I haven't seen any errors, and the node never stops working. However, when I make changes to the node's settings, those changes aren't reflected in Home Assistant or the MQTT broker. Even after waiting 20 hours, no updates occur. As soon as I reboot Node-RED, the changes appear in Home Assistant and the MQTT broker immediately.

**Comment by alexsahka** [comment] 2024-04-08 16:20
> Lastly what's the thinking for using that hass discovery node? I've never needed to do this and just added the MQTT extension in HASS settings to connect directly to MQTT.

The node-red-contrib-ha-mqtt integration includes an Auto-discovery node.  According to my understanding, any changes made to the settings within a node-red-contrib-ha-mqtt node require activating this Auto-discovery node.  This activation appears to be necessary for the changes to be reflected in the MQTT broker and subsequently pushed to Home Assistant.

**Comment by bryzix** [comment] 2024-04-08 16:50
> > Lastly what's the thinking for using that hass discovery node? I've never needed to do this and just added the MQTT extension in HASS settings to connect directly to MQTT.
> 
> The node-red-contrib-ha-mqtt integration includes an Auto-discovery node. According to my understanding, any changes made to the settings within a node-red-contrib-ha-mqtt node require activating this Auto-discovery node. This activation appears to be necessary for the changes to be reflected in the MQTT broker and subsequently pushed to Home Assistant.

Ok, however this should have nothing to do with the climate node as it already registers the correct MQTT message that will be discovered by HASS assuming you have installed the HA MQTT add in...

https://www.home-assistant.io/integrations/mqtt/

Im a bit confused with your set up now.  Are you able to share the larger flow so i can take a closer look please? feel free to email this to me if you dont wish to share here.

**Comment by bryzix** [comment] 2024-04-08 17:03
And for clarity the expected sequence of events you should expect are...

- After every node red deploy the climate node will...
  - write to the homeassistant/climate/\<entity id\>/climate/config MQTT topic containing the set up of the climate entity.  This is only config and does not contain actual values, e.g. setpoint or temperature
  - write to the \<root topic\>/\<entity id\>/... MQTT topic with the current values (\<root topic\> is configured in the node settings and should ideally not be within the homeassistant path)
- HASS will discover the entity (assuming you have the [MQTT add-in](https://www.home-assistant.io/integrations/mqtt/) configured in HASS, you should not need anything else)
- If you make a change in HASS e.g. set point, it will send a message to request a change via MQTT
  - if this change is successful the value in \<root topic\>/\<entity id\>/... would be updated
  - you would also see some values change on the node status itself
- If any values change during normal operation e.g. heat/cool output as a result of a temp change you will see this reflected in MQTT in \<root topic\>/\<entity id\>/...

As MQTT is the main communication point its important to make sure that nothing else is using these same topic paths

**Comment by alexsahka** [comment] 2024-04-08 17:10
> As MQTT is the main communication point its important to make sure that nothing else is using these same topic paths

I fully understand the importance of ensuring that nothing else is using these same topic paths.

**Comment by bryzix** [comment] 2024-04-09 11:07
Hi, ive uploaded 1.0.7 which shows in the node status if MQTT is enabled and is not connected.  my thinking is that this is conjunction with the node red log output should highligh any errors with MQTT dependencies.

Ive also created a video of my setup, fresh HASS install with mosquitto and your export which may be helpful reference...
https://1drv.ms/v/s!ApRXijjdDs-Ugr5Iwqv3lnEsLt6fvQ?e=ItSXHY

**Comment by alexsahka** [comment] 2024-04-09 19:23
> Hi, ive uploaded 1.0.7 which shows in the node status if MQTT is enabled and is not connected. my thinking is that this is conjunction with the node red log output should highligh any errors with MQTT dependencies.
> 
> Ive also created a video of my setup, fresh HASS install with mosquitto and your export which may be helpful reference... https://1drv.ms/v/s!ApRXijjdDs-Ugr5Iwqv3lnEsLt6fvQ?e=ItSXHY

Thanks for the video! Here's the current situation:

Temperature changes work from Home Assistant to Node-RED. I can see "Heat" and "Off" commands being sent from HA and received by Node-RED.
However, changes made within Node-RED itself, like switching from "heat only" to "cool only," aren't reflected in Home Assistant. 
Interestingly, injecting a temperature value directly into Node-RED does update Home Assistant.


Also, the MQTT 2 topic is created, I think it is suspicion:
![image](https://github.com/thingzi/thingzi-logic-climate/assets/7469537/47d1693b-e4ce-4016-b293-dc965496db4e)

![image](https://github.com/thingzi/thingzi-logic-climate/assets/7469537/0d9e0dd3-9596-4e17-9f67-03406866a541)

**Comment by bryzix** [comment] 2024-04-09 21:53
That 1st topic with the underscores is nothing to do with my climate node, is this created by node-red-contrib-ha-mqtt?.  the 2nd topic looks right though.  That 1st topic should be deleted/stopped as there is a potential for conflict if HASS thinks the ids match which may cause config/update issues.

On the NR settings, you can see me changing "heat only" to "cool only" at 00:30 in the video and the mode options change to match.  This just limits the available modes in the drop down but they still need to be selected in HASS or via a message to do anything.

**Comment by alexsahka** [comment] 2024-04-09 22:19
> That 1st topic with the underscores is nothing to do with my climate node, is this created by node-red-contrib-ha-mqtt?. the 2nd topic looks right though. That 1st topic should be deleted/stopped as there is a potential for conflict if HASS thinks the ids match which may cause config/update issues.
> 
> On the NR settings, you can see me changing "heat only" to "cool only" at 00:30 in the video and the mode options change to match. This just limits the available modes in the drop down but they still need to be selected in HASS or via a message to do anything.

Both topics start appearing as soon as I add a thingzi node to a clean Node-RED installation. However, the node-red-contrib-ha-mqtt nodes are not present in this Node-RED instance.

**Comment by alexsahka** [comment] 2024-04-10 03:50
> That 1st topic with the underscores is nothing to do with my climate node, is this created by node-red-contrib-ha-mqtt?. the 2nd topic looks right though. That 1st topic should be deleted/stopped as there is a potential for conflict if HASS thinks the ids match which may cause config/update issues.
> 
> On the NR settings, you can see me changing "heat only" to "cool only" at 00:30 in the video and the mode options change to match. This just limits the available modes in the drop down but they still need to be selected in HASS or via a message to do anything.

Both topics are flashing "update" in the MQTT Explorer whenever I change the input temperature or set temperature. However, the mode changes are not reflected in either MQTT or Home Assistant (HA) until I reboot Node-RED.

**Comment by bryzix** [comment] 2024-04-10 20:35
its possible HASS is reflecting this data back to MQTT based on your setup, the 1st topic ghheater_climate_ghheater is nothing to do with the thingzi node as it doest have the code to generate it.  Its still possible this is a source of conflict with the thingzi node so its worth understanding how its being created and remove it if you arent using it.

And to double check when you changed to "heat only" or "cool only" i would expect to see the JSON values in ghheater-climate/climate/config JSON change, e.g....

![Screenshot 2024-04-10 at 21 16 00](https://github.com/thingzi/thingzi-logic-climate/assets/46371227/e4349b3c-b1e7-41cd-981e-94c36765c5ab)

given that MQTT messages are flowing in both directions, i dont see any reason this topic would not update.  It may not be processed by HASS but it should change in MQTT.  I added a log entry to node red console in 1.0.6 that shows when this config is updated per node...

<img width="979" alt="image" src="https://github.com/thingzi/thingzi-logic-climate/assets/46371227/36411dc3-c4e8-4333-bb2d-c9a81520671c">

**Comment by alexsahka** [comment] 2024-04-11 07:09
> its possible HASS is reflecting this data back to MQTT based on your setup, the 1st topic ghheater_climate_ghheater is nothing to do with the thingzi node as it doest have the code to generate it. Its still possible this is a source of conflict with the thingzi node so its worth understanding how its being created and remove it if you arent using it.
> 
> And to double check when you changed to "heat only" or "cool only" i would expect to see the JSON values in ghheater-climate/climate/config JSON change, e.g....
> 
> ![Screenshot 2024-04-10 at 21 16 00](https://private-user-images.githubusercontent.com/46371227/321392339-e4349b3c-b1e7-41cd-981e-94c36765c5ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MTkwNzMsIm5iZiI6MTcxMjgxODc3MywicGF0aCI6Ii80NjM3MTIyNy8zMjEzOTIzMzktZTQzNDliM2MtYjFlNy00MWNkLTk4MWUtOTRjMzY3NjVjNWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA2NTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYTg2ZGIzMTM5MmQ1MTVmM2RkZGQ4MzExNjllNjc2NDRmODQ2MmUwYWRmMjI5ZDVjY2ViNTY0MDg0ZjI4ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.huArtT2KkWFZysJefi2q5ThZdlHuoT4a1ZsEpAujno8)
> 
> given that MQTT messages are flowing in both directions, i dont see any reason this topic would not update. It may not be processed by HASS but it should change in MQTT. I added a log entry to node red console in 1.0.6 that shows when this config is updated per node...
> 
> <img alt="image" width="979" src="https://private-user-images.githubusercontent.com/46371227/321395245-36411dc3-c4e8-4333-bb2d-c9a81520671c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MTkwNzMsIm5iZiI6MTcxMjgxODc3MywicGF0aCI6Ii80NjM3MTIyNy8zMjEzOTUyNDUtMzY0MTFkYzMtYzRlOC00MzMzLWJiMmQtYzlhODE1MjA2NzFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA2NTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZDIyY2U0MDJlNzVjZWUwODAxZjllNjdkYjg4MWJhM2U5OGMyZGJkYTA0MTM4NzcwNzRkYWFiMThiMzRmYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IqJZ1aBDfUJ6oHMpxSBH8NYwaWecbiwPC0LYfjZKT0w">
I don't see anything related to Advertise in the log.
No change in the ghheater-climate/climate/config JSON until Nodered reboot
![image](https://github.com/thingzi/thingzi-logic-climate/assets/7469537/02eb98af-0cbc-45ad-8cb7-2b320d9ac7fb)

![image](https://github.com/thingzi/thingzi-logic-climate/assets/7469537/8a2e8dc2-0268-42cf-8a3f-4d425ac25be9)

**Comment by bryzix** [comment] 2024-04-11 16:27
Ok, that log was super useful thanks as the line "Starting modified flows" tells me the cause.

Advertise events for climate are send on connection only and if updating just the modified flows will not disconnect/connect from/to MQTT.  To do this for now you can update everything...

<img width="321" alt="image" src="https://github.com/thingzi/thingzi-logic-climate/assets/46371227/3b70292d-9bdd-4cf7-9bad-f2cb1878d5f2">

In the mean time i will work on advertising working when deploying just the modified flows.  thanks!!

**Comment by alexsahka** [comment] 2024-04-11 16:49
> Advertise events for climate are send on connection only and if updating just the modified flows will not disconnect/connect from/to MQTT. To do this for now you can update everything...

Makes sense now! I successfully performed a Full Deploy, and now updates are published to both MQTT and Home Assistant whenever I make changes to the nodes. Thank you.

**Comment by bryzix** [comment] 2024-04-15 16:33
This should now be addressed in v1.1.0 which now supports modified flows/nodes.
Thanks for your help!

**Closed as completed by bryzix** 2024-04-15 16:33 UTC

**Comment by alexsahka** [comment] 2024-04-16 21:11
> This should now be addressed in v1.1.0 which now supports modified flows/nodes. Thanks for your help!

Thank you!
